export enum Utils {
  TITLE_SUCCESS = "UTILS.TITLE_SUCCESS",
  TITLE_ERROR = "UTILS.TITLE_ERROR",
  TITLE_CONFIRM = "UTILS.TITLE_CONFIRM",
  OK = "UTILS.OK",
  CLOSE = "UTILS.CLOSE",
  SAVE = "UTILS.SAVE",
  NOTICE_FROM_PAGE = "ページからの通知",
}

export enum VALIDATION {
  MIN_PASS = 6,
  MAX_PASS = 40,
  MAX_CARD = 19,
  MAX_CVV = 4,
  MIN_CVV = 3,
  MAX_YEAR = 2,
  MAX_MONTH = 2,
  NUMBER_SPACE = 4,
}

export enum WINDOWN_SIZE {
  LANDSCAPE = 1024,
  PHONE = 768,
}

export enum TYPE_BUTTON {
  DEFAULT = 1,
  PRIMARY = 2,
  SECCOND = 3,
  CHECKBOX = 4,
  THIRT = 5,
  YELLOW = 6,
}

export enum TYPE_CHECKBOX {
  DEFAULT = 1,
  BUTTON = 2,
  SWITCH = 3,
}

export enum TYPE_INPUT {
  TEXT = "text",
  RADIO = "radio",
}

export enum STEP_REGISTER {
  DEFAULT = 1,
  CONFIRM = 2,
  SUCCESS = 3,
}

export enum FORM_TYPE {
  REGISTER = "register",
  PROFILE = "profile",
}

export enum STATUS_MATCHING {
  MATCH = "MATCHING",
  NO_MATCH = "NO MATCHING",
}

export enum TYPE_TARGET_MATCHING {
  INFO_USER = 1,
  INFO_COMMENT = 2,
  EVALUATION_COMMENT = 3,
}

export enum INTEREST {
  FOOD = 1,
  HETEROSEXUAL_FRIENDSHIP = 2,
  SLEEP = 3,
  APPAREL = 4,
  BEAUTY_RELATED = 5,
  MONEY = 6,
}

export enum BUSINESS {
  PROFITABILITY = 1,
  HUMAN_RESOURCES = 2,
  HUMAN_RESOURCE_INTERNAL_STRUCTURE = 3,
  SALES_FORCE_SALES_CHANNEL = 4,
  SERVICE_IMPROVEMENT = 5,
  OFFICE_MANAGEMENT = 6,
}

export enum TYPE_MATCHING_LIST {
  REQUEST = 1,
  APPROVAL_PENDING = 2,
  MATCHED = 3,
}

export enum TYPE_REGISTER {
  INDIVIDUAL = 1,
  SOLE_PROPRIETORSHIP = 2,
  CORPORATION = 3,
}

export enum TYPE_SETTING_ABOUT {
  FREE = 1,
  VIZIEN = 2,
  VIZIEN_NEO = 3,
}

export enum HTTP_STATUS {
  UPGRADE = 406,
}

export enum TYPE_LIST_MATCHING {
  A = "A",
  B = "B",
  C = "C",
}
